### PR TITLE
Updated final installation setup script

### PR DESCRIPTION
**Pull request by gabiiiiiii**

### CODE REVIEW

**Comment by trel** [comment]
This works fine - please add a sentence afterwards about what that command does (uses the defaults in that file that are the same as what's in the table nearby).

**Comment by trel** [comment]
'underneith' -> 'underneath'

then we'll merge - thanks!

**Comment by trel** [comment]
you could squash them to a single commit if you're feeling adventurous

**Comment by gabiiiiiii** [comment]
oh no, well I used the amend command and I just added it again twice somehow

**Pull request merged**
