### PR TITLE
get SLURM working for data-to-compute on ubuntu20

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
I need to test from scratch on a fresh VM, and then will take out of draft status

**Comment by d-w-moore** [comment]
The slides can be dup'ed from https://slides.com/danielmoore-5/ugm-2023-data-to-compute

**Review by alanking — COMMENTED** [review]
Seems fine to me

**Comment by alanking** [comment]
Please note what changed in the slides so that they can be spotted easily as we review them. Thanks

**Comment by d-w-moore** [comment]
Done!

**Pull request merged**
